CREATE TABLE Stammdaten
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  quellregisterId VARCHAR(50) NOT NULL,
  stammdatenId VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
